#!/bin/bash
set -e

RG="rg-secure-infra-demo"
LOC="canadacentral"
KV="kvsecure6386"
VNET="vnet-secure-infra"
SUBNET="snet-app"

# Private Endpoint
az network private-endpoint create \
  --resource-group $RG \
  --name pe-kv \
  --vnet-name $VNET \
  --subnet $SUBNET \
  --private-connection-resource-id $(az keyvault show -n $KV -g $RG --query id -o tsv) \
  --group-id vault \
  --connection-name kv-pe-connection

# Private DNS Zone
az network private-dns zone create \
  --resource-group $RG \
  --name privatelink.vaultcore.azure.net

az network private-dns link vnet create \
  --resource-group $RG \
  --zone-name privatelink.vaultcore.azure.net \
  --name kv-dns-link \
  --virtual-network $VNET \
  --registration-enabled false

az network private-endpoint dns-zone-group create \
  --resource-group $RG \
  --endpoint-name pe-kv \
  --name kv-dns \
  --private-dns-zone privatelink.vaultcore.azure.net \
  --zone-name privatelink.vaultcore.azure.net

# Disable public access
az keyvault update \
  -n $KV \
  -g $RG \
  --public-network-access Disabled
